apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  containers:
  - name: meu-container
    image: nginx
    ports:
    - containerPort: 3000
    env:
      - name: URL_IMAGEM
        valueFrom:
          secretKeyRef:
            name: opaque-secret-image
            key: URL_IMAGEM
      - name: MONGO_URL
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: MONGO_URL
      - name: REDIS_URL
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: REDIS_URL
